#!/usr/bin/env ruby

ERR_CHANNEL = STDERR.dup
OUT_CHANNEL = STDOUT.dup

STDERR.reopen('/dev/null', 'w')
STDOUT.reopen('/dev/null', 'w')

def log(msg)
  File.open('/tmp/slog', 'a') { |f| f.puts "#{Time.now}: #{msg}"}
end

log 'start'

require 'json'
begin
  require_relative './ext'
rescue LoadError => e
  # TODO: decide what to do here
  log e
end

log 'booted'

while true
  log 'loop'
  input = JSON[STDIN.readline]
  log "read: #{input.inspect}"
  OUT_CHANNEL.puts input.to_json
  OUT_CHANNEL.flush
  log "wrote: #{input.to_json.inspect}"
end
