#!/usr/bin/env ruby

require 'json'

def log(msg)
  File.open('/tmp/slog', 'a') { |f| f.puts "#{Time.now}: #{msg}"}
end

log 'booted'

while true
  log 'loop'
  input = JSON[STDIN.readline]
  log "read: #{input.inspect}"
  STDOUT.puts input.to_json
  STDOUT.flush
  log "wrote: #{input.to_json.inspect}"
end
