name: clang-format

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  style:
    runs-on: ubuntu-22.04
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jidicula/clang-format-action@3a18028048f01a66653b4e3bf8d968d2e7e2cb8b # v4.17.0
        with:
          clang-format-version: "22"
          check-path: lua
